language: generic
sudo: required
servises:
  - docker

before_install:
  - docker build -t michaellennartsson/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true michaellennartsson/docker-react npm run test
